### ISSUE TITLE
Account Per Container Extension for Firefox

### ISSUE THREAD

**Issue by mpirhayati** [tiansh/account-per-container#1]
in the name of  GOD
hello
how to save password for each container?
Can you update your extension to enable save username and password for each container?
thanks.

**Comment by tiansh** [comment]
Just let Firefox's default password manager remembers the password. It should be filled automatically. In case it doesn't working for you: Could you please leave more information about your using including...
* Which website are you working on?
* May Firefox's default password manager recognize the password field and help you filling password automatically (when you disabled the extension)?

**Comment by mpirhayati** [comment]
> 
> 
> Just let Firefox's default password manager remembers the password. It should be filled automatically. In case it doesn't working for you: Could you please leave more information about your using including...
> 
>     * Which website are you working on?
> 
>     * May Firefox's default password manager recognize the password field and help you filling password automatically (when you disabled the extension)?

Excuse me. Account Per Container Extension doesn't work in this website:
https://account.emofid.com/Login
This extension icon isn't appear in address bar for this website.
how can I add rule manually?

**Comment by tiansh** [comment]
> Excuse me. Account Per Container Extension doesn't work in this website:
> https://account.emofid.com/Login

Thank you for your feedback. The extension didn't recognize a telephone number input as username. As the result, it failed to detect the login form. I will work on it and release an update this weekends. It should be fixed in a few days.

**Comment by tiansh** [comment]
The new version had been uploaded to AMO. You may update the extension and verify.

**Comment by mpirhayati** [comment]
> 
> 
> The new version had been uploaded to AMO. You may update the extension and verify.

I re-instal this extension. but the extension doesn't work for that site. This extension icon isn't appear in address bar for that website. how to add rule manually?

**Comment by tiansh** [comment]
> how to add rule manually?

1. Make sure you are using the newest (1.1.3) version of extension;
2. Make sure you opened the website in a container;
3. Type your username into the username input box
4. The icon should appear there.

Please let me know if you still cannot find the icon in the right most of address bar.

**Comment by mpirhayati** [comment]
> 
> 
> > how to add rule manually?
> 
>     1. Make sure you are using the newest (1.1.3) version of extension;
> 
>     2. Make sure you opened the website in a container;
> 
>     3. Type your username into the username input box
> 
>     4. The icon should appear there.
> 
> 
> Please let me know if you still cannot find the icon in the right most of address bar.

This extension icon isn't appear in address bar for that website yet still. Can you design a button for adding rule manually?

**Comment by mpirhayati** [comment]
in the name of  GOD

The extension works properly. Thanks for your response.

**Comment by tiansh** [comment]
> This extension icon isn't appear in address bar for that website yet still. Can you design a button for adding rule manually?

The extension cannot fill username automatically for you if it doesn't understand which input is used for username. So it is meaningless to manually edit the option.

The site you mentioned just works for me. I'm not sure what's going wrong on your browser.

**Comment by mpirhayati** [comment]
> 
> 
> > This extension icon isn't appear in address bar for that website yet still. Can you design a button for adding rule manually?
> 
> The extension cannot fill username automatically for you if it doesn't understand which input is used for username. So it is meaningless to manually edit the option.
> 
> The site you mentioned just works for me. I'm not sure what's going wrong on your browser.

This extension works properly. Thanks for your extension.
